# Disk parameters

ShockTube: '0'   # Initialize shocktube problem with 0:no shocktube 1:Ideal EOS (perfect gas) 2: PVTE EOS (variableGamma) [default = 0]
Sigma0: 1890.673 g/cm2   # surface density at r=1 in g/cm^2
SigmaSlope: '0.5'   # slope of surface density profile: Sigma(r) = Sigma0 * r^(-SigmaSlope)
SetSigma0: 'No'   # renormalize Sigma0 to have M_disc = discmass in units of m0 [default = no]
DiscMass: '0.5'   # only used when SetSigma0 = true [default = 0.01]
SigmaFloor: 1e-9   # floor surface density in multiples of sigma0 [default = 1e-9]
SigmaCondition: Profile   # Initialize surface density by Profile, 1D or 2D [default = Profile]
SigmaFilename: ''   # File to read surface density from (when Condition = 1D or 2D)
DensityFactor: '2.0'   # Factor for convertion from surface density to density [default = sqrt(2.0*pi)]
ProfileCutoffInner: 'No'   # enable profile cutoff [default = no]
ProfileCutoffPointInner: '4.0'   # in [L0], [default = 0]
ProfileCutoffWidthInner: '0.5'   # in [L0], [default = 1]
ProfileCutoffOuter: 'No'   # enable profile cutoff [default = no]
ProfileCutoffPointOuter: '40.0'   # in [L0], [default = 1e+300]
ProfileCutoffWidthOuter: '0.5'   # in [L0], [default = 1]
EnergyCondition: Profile   # Initialize energy by Profile, 1D or 2D [default = Profile]
EnergyFilename: ''   # File to read energy from (when Condition = 1D or 2D)
AspectRatio: '0.05'   # Thickness over Radius in the disk
AspectRatioMode: '0'   # Compute aspectratio with respect to: 0: Primary object, 1: Nbody system, 2: Nbody center of mass
TemperatureCGS0: '0.0'   # Midplane Temperature at 1 au in K, overwrites AspectRaio
ExplicitViscosity: 'YES'
StsNu: '0.01'
ViscosityInCGS: 'NO'   # Interpret Uniform kinematic viscosity (Viscosity below) in cgs units instead of code units
Viscosity: '0'   # Uniform kinematic viscosity
AlphaViscosity: '1.0e-3'   # 
StabilizeViscosity: '0'   # 1 for limiting viscosity update step, 2 for limiting dt
ArtificialViscosity: TW   # Type of artificial viscosity (none, TW, SN) [default = SN]
ArtificialViscosityDissipation: 'Yes'   # Use artificial viscosity in dissipation function [default = yes]
ArtificialViscosityFactor: '1.41'   # artificial viscosity factor/constant (von Neumann-Richtmyer constant) [default = 1.41]
FlaringIndex: '0.0'   # Slope of Temperature/radius profile
SelfGravity: 'No'   # choose: Yes, Z or No
EquationOfState: Ideal   # Isothermal Ideal PVTE Polytropic [default = Isothermal]
AdiabaticIndex: '1.4'   # numerical value or FIT_ISOTHERMAL (only for polytropic equation of state) [default = 1.4]
PolytropicConstant: FIT_ISOTHERMAL   # numerical value or FIT_ISOTHERMAL (only for polytropic equation of state) [default = 1.4]
CoolingRadiativeLocal: 'Yes'   # enable local radiative cooling Q- = 2 * sigma_R * T_eff^4 [default = no]
CoolingBetaLocal: 'No'   # enable beta cooling Q- = T * Omega/beta [default = no]
CoolingBeta: '10'
RadiativeDiffusion: 'No'   # 
RadiativeDiffusionOmega: '1.5'   # [default = 1.5]
RadiativeDiffusionAutoOmega: 'No'   # [default = no]
RadiativeDiffusionMaxIterations: '50000'   # [default = 50000]
HeatingViscous: 'Yes'   # enable viscous heating
HeatingViscousFactor: '1.0'
HeatingStar: 'No'
HeatingStarRampingTime: '5'   # Ramping time for star heating in timesteps
HeatingStarFactor: '1.0'
HeatingStarSimple: 'No'   # Use simplified star heating [default = No]
MinimumTemperature: 3 K   # minimum Temperature in K
MaximumTemperature: 1e100 K   # maximum Temperature in K
TauFactor: '1.0'   # correction factor for tau [default = 1.0]
Opacity: Lin   # opacity table to use (Lin, Bell, Zhu, Kramers) [default = Lin]
KappaConst: '2.0e-6'   # used for const and simple opacity (kappa = kappa0 * T**2)
CFL: '0.5'
HeatingCoolingCFLlimit: '1.0'   # energy change dT/T in substep3 only allowed to change by this fraction times CFL.

zbufferSize: '100'
zbufferMaxAngle: '0.174'

# Units

l0: 1 au   # Base length unit in times of 1 AU = 149597870691 m. A planet with an orbital radius of 1 l0 has an orbit time of 2PI. [default=1.0]
m0: '1 solMass'   # Base mass unit in times of solar mass = 1.98892e30 kg. The central star has a mass of 1 m0. [default=1.0]
mu: '2.35'   # mean molecular weight [default=1.0]
ImposedDiskDrift: '0.0'   # Impose a radial drift of the disk material (default = 0)
InitializePureKeplerian: 'No'   # Initialize VRadial=0 and VAzimuthal=(GM/r)^(1/2) (default = No)
InitializeVradialZero: 'No'   # Initialize VRadial=0  [default = no]
MassOverflow: 'No'   # [default = No]
mofValue: '1.0e-9 solMass/yr'   # flowrate in mass / time
mofPlanet: '1' # reference for the direction from which the mass overflow happens (mass flows in at the projected position of the planet at the outer boundary)
mofTemperature: '1500' 
mofRampingTime: '30' # in planetary orbits

# Planet parameters

SecondaryDisk: 'No'
ThicknessSmoothing: '0.6'   # Softening parameters in disk thickness [default = 0.0]
ThicknessSmoothingSG: '0.0'   # Softening parameter for SG [default = ThicknessSmoothing]

# Boundary layer parameters

VRadIn: 1e-3   # value of v_rad at inner boundary in terms of Keplerian velocity v_kepler at the inner boundary [default = 1.6e-3]
StellarRotation: '0.1'   # Stellar rotation rate (azimuthal velocity of the surface) in terms of Keplerian angular velocity at the inner boundary [default = 0.1]
MassAccretionRate: '1'   # Mass accretion rate (from secondary, young stellar cloud, etc.)
MassAccretionRadius: '0.2'   # Mass accretion radius in unints of R_hill / 2
KlahrSmoothingRadius: '0.2'   # Smoothing radius for Klahr & Kley smoothing around the secondary if HNbody is on
RadialViscosityFactor: '1'   # Viscosity in radial direction is mutliplied with this factor to avoid oscillations [default = 1]

# Numerical method parameters

Transport: FARGO

# InnerBoundary		NONREFLECTING	# Can also be OPEN, RIGID or NONREFLECTING, EVANESCENT, BoundaryLayer, PRESCRIBED_TIME_VARIABLE, ZERO_GRADIENT

InnerBoundary: OPEN
OuterBoundary: EVANESCENT
PrescribedBoundaryFileOuter: boundary_data_folder   # Only needed when PRESCRIBED_TIME_VARIABLE is active
DomegaDrZero: 'No'   # Set dOmega/dr = 0 at outer boundary
Damping: 'Yes'   # NO, YES [default = no]
DampingInnerLimit: '1.10'   # Rmin*Limit
DampingOuterLimit: '0.90'   # Rmax*Limit
DampingTimeFactor: '1.0e-3'
DampingEnergyInner: Initial   # Damping of energy at inner boundary, values: initial, mean, zero, none [default = none]
DampingVRadialInner: Initial   # Damping of radial velocity at inner boundary, values: initial, mean, zero, none [default = none]
DampingVAzimuthalInner: Initial   # Damping of azimuthal velocity at inner boundary, values: initial, mean, zero, none [default = none]
DampingSurfaceDensityInner: Initial   # Damping of surface density at inner boundary, values: initial, mean, zero, none [default = none]
DampingEnergyOuter: Initial   # Damping of energy at outer boundary, values: initial, mean, zero, none [default = none]
DampingVRadialOuter: Initial   # Damping of radial velocity at outer boundary, values: initial, mean, zero, none [default = none]
DampingVAzimuthalOuter: Initial   # Damping of azimuthal velocity at outer boundary, values: initial, mean, zero, none [default = none]
DampingSurfaceDensityOuter: Initial   # Damping of surface density at outer boundary, values: initial, mean, zero, none [default = none]
Disk: 'YES'
OmegaFrame: '1.0'
Frame: F   # F: Fixed, C: Corotating, G: Guiding-Center
DiskFeedback: 'NO'   # Calculate incfluence of the disk on the star

# Mesh parameters

Nrad: '128'   # 512 128		# Radial number of zones
Nsec: '384'   # 1536 384		# Azimuthal number of

# zones (sectors)

Rmin: '0.4'   # Inner boundary radius
Rmax: '2.5'   # Outer boundary radius
RadialSpacing: Logarithmic   # Logarithmic or ARITHMETIC or Exponential
ExponentialCellSizeFactor: '1.41'   # Scaling used on the size of the first cell in the logarithmic grid used to build an exponential grid
QuantitiesRadiusLimit: '2.5'   # Disk quantities will be computed only within this radius

# Output control parameters

Ntot: '2'   # Total number of time steps
Ninterm: '1'   # Time steps between outputs
DT: '0.628'   # Time step length. 2PI = 1 orbit
FirstDT: '1.0e-1'
CFLmaxVar: '1.1'
OutputDir: output/out
LogAfterRealSeconds: '600'
LogAfterSteps: '0'
DebugOutputs: 'No'
DoWrite1DFiles: 'No'
WriteAtEveryTimestep: 'Yes'   # Write some quantities (planet positions, disk quantities, ...) at every Timestep (ignore Ninterm) [default = no]
WriteDensity: 'Yes'   # Write surface density. This is needed for restart of simulations. [default = yes]
WriteEnergy: 'Yes'   # Write energy. This is needed for restart of (adiabatic) simulations. [default = yes]
WriteTemperature: 'No'   # Write temperature. [default = no]
WriteVelocity: 'Yes'   # Write velocites. This is needed for restart of simulations. [default = yes]
WriteSoundspeed: 'No'   # Write sound speed [default = no]
WriteEffectiveGamma: 'No'   # 
WriteFirstAdiabaticIndex: 'No'   # Usefull for PVTE EoS
WriteMeanMolecularWeight: 'No'   # 
WriteToomre: 'No'   # Write Toomre parameter Q. [default = no]
WriteQMinus: 'No'   # Write QMinus. [default = no]
WriteQPlus: 'No'   # Write QPlus. [default = no]
WriteViscosity: 'No'   # Write Viscosity. [default = no]
WriteTauCool: 'No'   # Write TauCool. [default = no]
WriteKappa: 'No'   # Write Kappa. [default = no]
WriteAlphaGrav: 'No'   # Write AlphaGrav. [default = no]
WriteAlphaGravMean: 'No'   # Write AlphaGrav time average. [default = no]
WriteAlphaReynolds: 'No'   # Write AlphaReynolds [default = no]
WriteAlphaReynoldsMean: 'No'   # Write AlphaReynolds time average [default = no]
WriteEccentricity: 'No'   # Write eccentricity. [default = no]
WriteTReynolds: 'No'   # Write Reynolds stress tensor. [default = no]
WriteTGravitational: 'No'   # Write gravitational stress tensor. [default = no]
WritepdV: 'No'   # Write pdV. [default = no]
WriteDiskQuantities: 'Yes'   # Write disk quantities (eccentricity, periastron, semi_major_axis) [default = no]
WriteRadialLuminosity: 'No'   # Write radial luminosity [default = no]
WriteRadialDissipation: 'No'   # Write radial dissipation [default = no]
WriteLightCurves: 'No'   # Write light curves [default = no]
WriteLightcurvesRadii: 0.4,5.2
WriteMassFlow: 'No'   # Write a 1d radial file with mass flow at each interface [default = no]
WriteGasTorques: 'No'   # Calculate and write gravitational/viscous and advection torques on gas. See Miranda et al. 2017
WritePressure: 'No'   # Write pressure [default = no]
WriteScaleHeight: 'No'   # Write scale height H [default = no]
WriteAspectratio: 'No'   # Write aspectratio h = H/r [default = no]
WriteTorques: 'No'   # Calculate and write torques acting in planet/star
WriteVerticalOpticalDepth: 'No'   # Write optical depth in vertical direction (tau_eff by Hubeny [1990])
RandomSeed: '1337'   # random seed integer value
RandomSigma: 'No'   # randomize sigma start values?
RandomFactor: '0.1'   # randomize by +- 10%
FeatureSize: '0.05'   # Feature size of the open somplex algorithm

# particles

IntegrateParticles: yes   # enable particle integrator [default = no]
CartesianParticles: 'YES'   # enable particle integrator [default = no]
ParticleIntegrator: Adaptive   # Explicit, Adaptive, Semiimplicit and Implicit
NumberOfParticles: '2000'   # number of particles [default = 0]
ParticleRadius: 1e5 cm   # particle radius in cm [default = 100]
ParticleEccentricity: '0.03'   # particle maximum Eccentricity
ParticleDensity: 2.65 g/cm3   # particle density in g/cm^3 [default = 2.65, Siliciumdioxid]
ParticleSurfaceDensitySlope: '0.5'   # [default = SigmaSlope] slope of particle surface density distribution: Sigma(r) = Sigma0 * r^(-ParticleSurfaceDensitySlope)
ParticleMinimumRadius: '0.4'   # [default = RMIN]
ParticleMaximumRadius: '2.5'   # [default = RMAX]
ParticleMinimumEscapeRadius: '0.4'   # [default = ParticleMinimumRadius]
ParticleMaximumEscapeRadius: '2.5'   # [default = ParticleMaximumRadius]
ParticleGasDragEnabled: 'yes'   # [default = YES]
ParticleDiskGravityEnabled: 'no'   # [default = no]

# Planets

HydroFrameCenter: primary   # specify the origin of the simulation grid. Primary uses the central object, binary/tertiary/quatirary/all uses the center of mass of the first 2/3/4/all nbody objects
BodyForceFromPotential: 'Yes'
IntegratePlanets: 'Yes'   # [default = yes]

# Star Parameters

StarRadius: '1.0'   # star radius in Solar Radii
StarTemperature: '5778'   # star temperature in K

nbody:
- name: Star
  semi-major axis: 0.0 au
  mass: 1.0 solMass
  eccentricity: 0.0
  temperature:
  radius: 1.0 solRadius
  temperature: 5778 K
- name: Jupiter
  semi-major axis: '1.0'
  mass: 3e-4
  accretion efficiency: '0.0'
  eccentricity: '0'
  radius: 0.01 solRadius
  temperature: 5800 K
  irradiate: 'NO'
  phi: '0.0'
  ramp-up time: '0.0'
